#!/usr/bin/env ruby
# encoding: utf-8

require "rubygems"
require "ywx"

CONDITION_SYMBOLS = {
  normal: "●",
  snow: "❄",
  rain: "☂",
  sunny: "☀",
  cloudy: "☁",
  crazy: "",
  windy: "",
  not_available: "N/A"
}

# http://developer.yahoo.com/weather/#codes
CONDITION_CODES = {
  0 => :crazy,
  1 => :rain,
  2 => :rain,
  3 => :rain,
  4 => :rain,
  5 => :snow,
  6 => :snow,
  7 => :snow,
  8 => :snow,
  9 => :rain,
  10 => :snow,
  11 => :rain,
  12 => :rain,
  13 => :snow,
  14 => :snow,
  15 => :snow,
  16 => :snow,
  17 => :snow,
  18 => :snow,
  19 => :crazy,
  20 => :cloudy,
  21 => :cloudy,
  22 => :crazy,
  23 => :windy,
  24 => :windy,
  25 => :snow,
  26 => :cloudy,
  27 => :cloudy,
  28 => :cloudy,
  29 => :cloudy,
  30 => :cloudy,
  31 => :normal,
  32 => :sunny,
  33 => :normal,
  34 => :sunny,
  35 => :rain,
  36 => :sunny,
  37 => :rain,
  38 => :rain,
  39 => :rain,
  40 => :rain,
  41 => :snow,
  42 => :snow,
  43 => :snow,
  44 => :cloudy,
  45 => :rain,
  46 => :snow,
  47 => :rain,
  3200 => :not_available
}

@client = YahooWeather::Client.new(ENV["WEATHER_YAHOO_APP_ID"])

result = @client.lookup_zip(ENV["WEATHER_ZIP_CODE"])

condition = CONDITION_SYMBOLS[CONDITION_CODES[result.condition.code]]
temp = result.condition.temp

daylight = if result.astronomy.sunrise < Time.now && result.astronomy.sunset > Time.now
  ""
else
  "☽ "
end

puts "#{daylight}#{condition} #{temp}°"